/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as DashboardRestaurantRouteImport } from './routes/dashboard.restaurant'
import { Route as DashboardLivreurRouteImport } from './routes/dashboard.livreur'
import { Route as DashboardAmbassadeurRouteImport } from './routes/dashboard.ambassadeur'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/restaurants/',
  path: '/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/restaurants/$id',
  path: '/restaurants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRestaurantRoute = DashboardRestaurantRouteImport.update({
  id: '/dashboard/restaurant',
  path: '/dashboard/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLivreurRoute = DashboardLivreurRouteImport.update({
  id: '/dashboard/livreur',
  path: '/dashboard/livreur',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAmbassadeurRoute = DashboardAmbassadeurRouteImport.update({
  id: '/dashboard/ambassadeur',
  path: '/dashboard/ambassadeur',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/dashboard/ambassadeur': typeof DashboardAmbassadeurRoute
  '/dashboard/livreur': typeof DashboardLivreurRoute
  '/dashboard/restaurant': typeof DashboardRestaurantRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/restaurants/': typeof RestaurantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/dashboard/ambassadeur': typeof DashboardAmbassadeurRoute
  '/dashboard/livreur': typeof DashboardLivreurRoute
  '/dashboard/restaurant': typeof DashboardRestaurantRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/restaurants': typeof RestaurantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/dashboard/ambassadeur': typeof DashboardAmbassadeurRoute
  '/dashboard/livreur': typeof DashboardLivreurRoute
  '/dashboard/restaurant': typeof DashboardRestaurantRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/restaurants/': typeof RestaurantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/login'
    | '/orders'
    | '/register'
    | '/dashboard/ambassadeur'
    | '/dashboard/livreur'
    | '/dashboard/restaurant'
    | '/restaurants/$id'
    | '/restaurants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/login'
    | '/orders'
    | '/register'
    | '/dashboard/ambassadeur'
    | '/dashboard/livreur'
    | '/dashboard/restaurant'
    | '/restaurants/$id'
    | '/restaurants'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/login'
    | '/orders'
    | '/register'
    | '/dashboard/ambassadeur'
    | '/dashboard/livreur'
    | '/dashboard/restaurant'
    | '/restaurants/$id'
    | '/restaurants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  DashboardAmbassadeurRoute: typeof DashboardAmbassadeurRoute
  DashboardLivreurRoute: typeof DashboardLivreurRoute
  DashboardRestaurantRoute: typeof DashboardRestaurantRoute
  RestaurantsIdRoute: typeof RestaurantsIdRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/restaurant': {
      id: '/dashboard/restaurant'
      path: '/dashboard/restaurant'
      fullPath: '/dashboard/restaurant'
      preLoaderRoute: typeof DashboardRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/livreur': {
      id: '/dashboard/livreur'
      path: '/dashboard/livreur'
      fullPath: '/dashboard/livreur'
      preLoaderRoute: typeof DashboardLivreurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ambassadeur': {
      id: '/dashboard/ambassadeur'
      path: '/dashboard/ambassadeur'
      fullPath: '/dashboard/ambassadeur'
      preLoaderRoute: typeof DashboardAmbassadeurRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  DashboardAmbassadeurRoute: DashboardAmbassadeurRoute,
  DashboardLivreurRoute: DashboardLivreurRoute,
  DashboardRestaurantRoute: DashboardRestaurantRoute,
  RestaurantsIdRoute: RestaurantsIdRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
